require('dotenv').config();
const express = require('express');
const cors = require('cors');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { Pool } = require('pg');

const app = express();
app.use(cors({origin:true}));
app.use(express.json({limit:'4mb'}));

const PORT = process.env.PORT || 3000;
const SECRET = process.env.JWT_SECRET || 'CHANGE_ME_IN_RENDER';
const ADMIN_USERNAME = 'Usman';
const ADMIN_EMAIL = 'admin@alfauzan.com';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'Us@#1234';
const pool = new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});

const sql = async (text, params=[]) => (await pool.query(text,params)).rows;
const n = (v,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d};
const norm = v=>String(v??'').trim();
function grade(total){const x=n(total); if(x<40)return {code:'POOR',label:'كسلان / Poor',color:'#b42318',fail:true}; if(x<60)return {code:'PASS',label:'مقبول / Pass',color:'#173b8f',fail:false}; if(x<70)return {code:'GOOD',label:'جيد / Good',color:'#245c2a',fail:false}; if(x<80)return {code:'VERY_GOOD',label:'جيد جداً / Very Good',color:'#245c2a',fail:false}; return {code:'EXCELLENT',label:'ممتاز / Excellent',color:'#245c2a',fail:false}}
function signToken(u){return jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'12h'})}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);if(req.user.role!=='admin'){const cfg=(await sql('SELECT system_open FROM settings WHERE id=1'))[0];if(cfg && cfg.system_open===false)return res.status(503).json({error:'The software is currently closed by the Administrator.'})}next()}catch(e){if(e&&e.status) return res.status(e.status).json({error:e.message});res.status(401).json({error:'Unauthorized'})}}
function only(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'})}
async function teacherCanClass(teacherId,classId){return (await sql('SELECT 1 FROM teacher_assignments WHERE teacher_id=$1 AND class_id=$2 LIMIT 1',[teacherId,classId])).length>0}
async function teacherCanSubject(teacherId,classId,subjectId){return (await sql('SELECT 1 FROM teacher_assignments WHERE teacher_id=$1 AND class_id=$2 AND subject_id=$3 LIMIT 1',[teacherId,classId,subjectId])).length>0}

const SCHEMA=`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,email TEXT,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('admin','teacher','student')),status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS classes(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS subjects(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS students(id SERIAL PRIMARY KEY,name TEXT NOT NULL,class_id INT REFERENCES classes(id) ON DELETE SET NULL,user_id INT UNIQUE REFERENCES users(id) ON DELETE SET NULL,admission_no TEXT UNIQUE,created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS teacher_assignments(id SERIAL PRIMARY KEY,teacher_id INT REFERENCES users(id) ON DELETE CASCADE,class_id INT REFERENCES classes(id) ON DELETE CASCADE,subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,UNIQUE(teacher_id,class_id,subject_id));
CREATE TABLE IF NOT EXISTS marks(id SERIAL PRIMARY KEY,student_id INT REFERENCES students(id) ON DELETE CASCADE,subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,test1 NUMERIC DEFAULT 0,test2 NUMERIC DEFAULT 0,exam NUMERIC DEFAULT 0,total NUMERIC DEFAULT 0,manual_total NUMERIC,manual_grade TEXT,updated_by INT REFERENCES users(id),updated_at TIMESTAMP DEFAULT now(),UNIQUE(student_id,subject_id));
CREATE TABLE IF NOT EXISTS attendance(id SERIAL PRIMARY KEY,student_id INT REFERENCES students(id) ON DELETE CASCADE,date DATE NOT NULL DEFAULT current_date,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(id INT PRIMARY KEY,school_name TEXT,school_address TEXT,session TEXT,term TEXT,report_date DATE,developer_name TEXT,developer_year TEXT,system_open BOOLEAN DEFAULT TRUE,report_hold BOOLEAN DEFAULT FALSE,payment_link TEXT DEFAULT '',maintenance_message TEXT DEFAULT 'The school portal is temporarily closed by the Administrator.');
ALTER TABLE settings ADD COLUMN IF NOT EXISTS system_open BOOLEAN DEFAULT TRUE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS report_hold BOOLEAN DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS payment_link TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS maintenance_message TEXT DEFAULT 'The school portal is temporarily closed by the Administrator.';
CREATE TABLE IF NOT EXISTS fees(id SERIAL PRIMARY KEY,student_id INT REFERENCES students(id) ON DELETE CASCADE,description TEXT NOT NULL,amount NUMERIC DEFAULT 0,paid_amount NUMERIC DEFAULT 0,due_date DATE,status TEXT DEFAULT 'Unpaid',created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS notices(id SERIAL PRIMARY KEY,title TEXT NOT NULL,message TEXT NOT NULL,audience TEXT DEFAULT 'all',created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS inventory(id SERIAL PRIMARY KEY,item_name TEXT UNIQUE NOT NULL,quantity NUMERIC DEFAULT 0,unit TEXT DEFAULT 'pcs',reorder_level NUMERIC DEFAULT 5,updated_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS report_meta(id SERIAL PRIMARY KEY,student_id INT UNIQUE REFERENCES students(id) ON DELETE CASCADE,position TEXT,out_of TEXT,attendance_override TEXT,teacher_remarks TEXT DEFAULT '',headmaster_remarks TEXT DEFAULT '',report_date DATE,updated_at TIMESTAMP DEFAULT now());
`;
async function init(){
  await pool.query(SCHEMA);
  await sql(`INSERT INTO settings(id,school_name,school_address,session,term,report_date,developer_name,developer_year,system_open,report_hold,payment_link,maintenance_message) VALUES(1,$1,$2,$3,$4,CURRENT_DATE,$5,$6,TRUE,FALSE,'','The school portal is temporarily closed by the Administrator.') ON CONFLICT(id) DO NOTHING`,['AL-FAUZAN CENTER FOR QUR\'AN AND GENERAL STUDIES','KUKAR AUWALE, ALIERO, KEBBI STATE','2025/2026','First Term','Usman Adamu Auwal','2025/2026']);
  for(const c of ['Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6']) await sql('INSERT INTO classes(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[c]);
  for(const s of ["Al-Qur'an",'Hadith','Tawheed','Fiqh','Tajweed','Arabic Language','Al-Huroof','Seerah']) await sql('INSERT INTO subjects(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[s]);
  const hash=await bcrypt.hash(ADMIN_PASSWORD,12);
  await sql(`INSERT INTO users(name,username,email,password_hash,role,status) VALUES($1,$2,$3,$4,'admin','active') ON CONFLICT(username) DO UPDATE SET name=EXCLUDED.name,email=EXCLUDED.email,password_hash=EXCLUDED.password_hash,role='admin',status='active'`,['Usman Adamu Auwal',ADMIN_USERNAME,ADMIN_EMAIL,hash]);
}

app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'Al-Fauzan SMS',version:'2.0'})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const name=norm(req.body.name),username=norm(req.body.username),email=norm(req.body.email)||null,password=String(req.body.password||'');if(!name||!username||password.length<6)return res.status(400).json({error:'Name, username and password (6+ characters) are required.'});if(username.toLowerCase()===ADMIN_USERNAME.toLowerCase())return res.status(400).json({error:'That username is reserved.'});const hash=await bcrypt.hash(password,12);const r=await sql(`INSERT INTO users(name,username,email,password_hash,role,status) VALUES($1,$2,$3,$4,'teacher','pending') RETURNING id,name,username,email,status`,[name,username,email,hash]);res.json({...r[0],message:'Registration submitted. Wait for Admin approval.'})}catch(e){res.status(400).json({error:'Username already exists or data is invalid.'})}});
app.post('/api/auth/login',async(req,res)=>{try{const username=norm(req.body.username),password=String(req.body.password||'');const r=await sql('SELECT * FROM users WHERE LOWER(username)=LOWER($1) LIMIT 1',[username]);if(!r.length||r[0].status!=='active')return res.status(401).json({error:'Invalid login or account is not approved.'});if(!(await bcrypt.compare(password,r[0].password_hash)))return res.status(401).json({error:'Invalid username or password.'});const u=r[0];res.json({token:signToken(u),user:{id:u.id,name:u.name,username:u.username,email:u.email,role:u.role,status:u.status}})}catch(e){res.status(500).json({error:'Login failed.'})}});
app.get('/api/me',auth,async(req,res)=>{const r=await sql('SELECT id,name,username,email,role,status FROM users WHERE id=$1',[req.user.id]);r.length?res.json(r[0]):res.status(404).json({error:'User not found.'})});

app.get('/api/admin/dashboard',auth,only('admin'),async(_req,res)=>{const [t,s,c,sub,p]=await Promise.all([sql("SELECT COUNT(*)::int n FROM users WHERE role='teacher'"),sql('SELECT COUNT(*)::int n FROM students'),sql('SELECT COUNT(*)::int n FROM classes'),sql('SELECT COUNT(*)::int n FROM subjects'),sql("SELECT id,name,username,email,status FROM users WHERE role='teacher' AND status='pending' ORDER BY name")]);const [f,i]=await Promise.all([sql('SELECT COUNT(*)::int n FROM fees'),sql('SELECT COUNT(*)::int n FROM inventory')]);res.json({teachers:t[0].n,students:s[0].n,classes:c[0].n,subjects:sub[0].n,fees:f[0].n,inventory:i[0].n,pending:p})});
app.get('/api/admin/teachers',auth,only('admin'),async(_req,res)=>res.json(await sql("SELECT id,name,username,email,status FROM users WHERE role='teacher' ORDER BY name")));
app.post('/api/admin/teachers/:id/approve',auth,only('admin'),async(req,res)=>{await sql("UPDATE users SET status='active' WHERE id=$1 AND role='teacher'",[req.params.id]);res.json({ok:true})});
app.post('/api/admin/teachers/:id/reject',auth,only('admin'),async(req,res)=>{await sql("UPDATE users SET status='rejected' WHERE id=$1 AND role='teacher'",[req.params.id]);res.json({ok:true})});
app.get('/api/classes',auth,async(req,res)=>{if(req.user.role==='teacher')return res.json(await sql('SELECT DISTINCT c.* FROM classes c JOIN teacher_assignments a ON a.class_id=c.id WHERE a.teacher_id=$1 ORDER BY c.name',[req.user.id]));if(req.user.role==='student')return res.json(await sql('SELECT c.* FROM classes c JOIN students s ON s.class_id=c.id WHERE s.user_id=$1',[req.user.id]));res.json(await sql('SELECT * FROM classes ORDER BY name'))});
app.get('/api/subjects',auth,async(req,res)=>{if(req.user.role==='teacher')return res.json(await sql('SELECT DISTINCT s.* FROM subjects s JOIN teacher_assignments a ON a.subject_id=s.id WHERE a.teacher_id=$1 ORDER BY s.name',[req.user.id]));if(req.user.role==='student')return res.json(await sql('SELECT DISTINCT s.* FROM subjects s JOIN marks m ON m.subject_id=s.id JOIN students st ON st.id=m.student_id WHERE st.user_id=$1 ORDER BY s.name',[req.user.id]));res.json(await sql('SELECT * FROM subjects ORDER BY name'))});
app.post('/api/classes',auth,only('admin'),async(req,res)=>{try{res.json((await sql('INSERT INTO classes(name) VALUES($1) RETURNING *',[norm(req.body.name)]))[0])}catch(e){res.status(400).json({error:'Class already exists or is empty.'})}});
app.post('/api/subjects',auth,only('admin'),async(req,res)=>{try{res.json((await sql('INSERT INTO subjects(name) VALUES($1) RETURNING *',[norm(req.body.name)]))[0])}catch(e){res.status(400).json({error:'Subject already exists or is empty.'})}});

app.get('/api/students',auth,async(req,res)=>{let where='',p=[];if(req.user.role==='teacher'){where='WHERE EXISTS(SELECT 1 FROM teacher_assignments a WHERE a.teacher_id=$1 AND a.class_id=s.class_id)';p=[req.user.id]}else if(req.user.role==='student'){where='WHERE s.user_id=$1';p=[req.user.id]}res.json(await sql(`SELECT s.id,s.name,s.class_id,c.name class_name,s.admission_no,u.username,u.status user_status FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN users u ON u.id=s.user_id ${where} ORDER BY s.name`,p))});
app.post('/api/students',auth,only('admin','teacher'),async(req,res)=>{try{const name=norm(req.body.name),classId=n(req.body.class_id),username=norm(req.body.username),password=String(req.body.password||''),admission=norm(req.body.admission_no)||null;if(!name||!classId||!username||password.length<6)return res.status(400).json({error:'Student name, class, username and password (6+ chars) are required.'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,classId))return res.status(403).json({error:'This class is not assigned to you.'});const hash=await bcrypt.hash(password,12);const u=(await sql(`INSERT INTO users(name,username,password_hash,role,status) VALUES($1,$2,$3,'student','active') RETURNING id`,[name,username,hash]))[0];const st=(await sql('INSERT INTO students(name,class_id,user_id,admission_no) VALUES($1,$2,$3,$4) RETURNING *',[name,classId,u.id,admission]))[0];res.json(st)}catch(e){res.status(400).json({error:'Student username or admission number already exists.'})}});
app.put('/api/students/:id',auth,only('admin','teacher'),async(req,res)=>{const id=n(req.params.id);const st=(await sql('SELECT * FROM students WHERE id=$1',[id]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,st.class_id))return res.status(403).json({error:'Forbidden'});const name=norm(req.body.name)||st.name,classId=n(req.body.class_id,st.class_id);if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,classId))return res.status(403).json({error:'Class not assigned.'});await sql('UPDATE students SET name=$1,class_id=$2,admission_no=$3 WHERE id=$4',[name,classId,norm(req.body.admission_no)||null,id]);if(st.user_id)await sql('UPDATE users SET name=$1 WHERE id=$2',[name,st.user_id]);res.json({ok:true})});

app.get('/api/marks/:studentId',auth,async(req,res)=>{const sid=n(req.params.studentId);const st=(await sql('SELECT * FROM students WHERE id=$1',[sid]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='student'&&st.user_id!==req.user.id)return res.status(403).json({error:'Forbidden'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,st.class_id))return res.status(403).json({error:'Forbidden'});const rows=await sql(`SELECT sub.id subject_id,sub.name subject,COALESCE(m.test1,0) test1,COALESCE(m.test2,0) test2,COALESCE(m.exam,0) exam,COALESCE(m.total,0) total,m.manual_total,m.manual_grade FROM subjects sub LEFT JOIN marks m ON m.subject_id=sub.id AND m.student_id=$1 ORDER BY sub.id`,[sid]);res.json(rows.map(r=>({...r,total:n(r.total),grade:r.manual_grade||grade(r.total).label,grade_color:r.manual_grade?( /poor|كسلان|fail|راسب/i.test(r.manual_grade)?'#b42318':'#17351f'):grade(r.total).color,fail:r.manual_grade?/poor|كسلان|fail|راسب/i.test(r.manual_grade):grade(r.total).fail})))});
app.post('/api/marks',auth,only('admin','teacher'),async(req,res)=>{const sid=n(req.body.student_id),sub=n(req.body.subject_id),t1=n(req.body.test1),t2=n(req.body.test2),ex=n(req.body.exam);if(t1<0||t1>20||t2<0||t2>20||ex<0||ex>60)return res.status(400).json({error:'Test 1 0-20, Test 2 0-20, Exam 0-60.'});const st=(await sql('SELECT * FROM students WHERE id=$1',[sid]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='teacher'&&!await teacherCanSubject(req.user.id,st.class_id,sub))return res.status(403).json({error:'You are not assigned this subject for this class.'});let mt=req.body.manual_total===''||req.body.manual_total==null?null:n(req.body.manual_total);if(mt!==null&&(mt<0||mt>100))return res.status(400).json({error:'Manual total must be 0-100.'});const mg=norm(req.body.manual_grade)||null;const r=await sql(`INSERT INTO marks(student_id,subject_id,test1,test2,exam,total,manual_total,manual_grade,updated_by) VALUES($1,$2,$3,$4,$5,COALESCE($6,$3+$4+$5),$6,$7,$8) ON CONFLICT(student_id,subject_id) DO UPDATE SET test1=$3,test2=$4,exam=$5,total=COALESCE($6,$3+$4+$5),manual_total=$6,manual_grade=$7,updated_by=$8,updated_at=now() RETURNING *`,[sid,sub,t1,t2,ex,mt,mg,req.user.id]);res.json(r[0])});

app.get('/api/attendance/:studentId',auth,async(req,res)=>{const sid=n(req.params.studentId);const st=(await sql('SELECT * FROM students WHERE id=$1',[sid]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='student'&&st.user_id!==req.user.id)return res.status(403).json({error:'Forbidden'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,st.class_id))return res.status(403).json({error:'Forbidden'});res.json(await sql('SELECT * FROM attendance WHERE student_id=$1 ORDER BY date DESC,id DESC',[sid]))});
app.post('/api/attendance',auth,only('admin','teacher'),async(req,res)=>{const sid=n(req.body.student_id),status=norm(req.body.status);if(!['Present','Absent','Late','Excused'].includes(status))return res.status(400).json({error:'Invalid status.'});const st=(await sql('SELECT * FROM students WHERE id=$1',[sid]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,st.class_id))return res.status(403).json({error:'Forbidden'});res.json((await sql('INSERT INTO attendance(student_id,date,status) VALUES($1,COALESCE($2,current_date),$3) RETURNING *',[sid,req.body.date||null,status]))[0])});

app.get('/api/admin/assignments',auth,only('admin'),async(_req,res)=>res.json(await sql(`SELECT a.*,u.name teacher,c.name class_name,s.name subject FROM teacher_assignments a JOIN users u ON u.id=a.teacher_id JOIN classes c ON c.id=a.class_id JOIN subjects s ON s.id=a.subject_id ORDER BY u.name,c.name,s.name`)));
app.post('/api/admin/assignments',auth,only('admin'),async(req,res)=>{try{res.json((await sql('INSERT INTO teacher_assignments(teacher_id,class_id,subject_id) VALUES($1,$2,$3) RETURNING *',[n(req.body.teacher_id),n(req.body.class_id),n(req.body.subject_id)]))[0])}catch(e){res.status(400).json({error:'Assignment already exists.'})}});
app.delete('/api/admin/assignments/:id',auth,only('admin'),async(req,res)=>{await sql('DELETE FROM teacher_assignments WHERE id=$1',[req.params.id]);res.json({ok:true})});

app.get('/api/fees',auth,async(req,res)=>{if(req.user.role==='student'){const s=(await sql('SELECT id FROM students WHERE user_id=$1',[req.user.id]))[0];if(!s)return res.json([]);return res.json(await sql("SELECT * FROM fees WHERE student_id=$1 ORDER BY due_date DESC,id DESC",[s.id]));} if(req.user.role==='teacher')return res.json(await sql("SELECT f.*,s.name student_name FROM fees f JOIN students s ON s.id=f.student_id WHERE s.class_id IN (SELECT class_id FROM teacher_assignments WHERE teacher_id=$1) ORDER BY f.id DESC",[req.user.id])); res.json(await sql("SELECT f.*,s.name student_name,c.name class_name FROM fees f JOIN students s ON s.id=f.student_id LEFT JOIN classes c ON c.id=s.class_id ORDER BY f.id DESC"));});
app.post('/api/fees',auth,only('admin','teacher'),async(req,res)=>{const sid=n(req.body.student_id),amount=n(req.body.amount),paid=n(req.body.paid_amount),description=norm(req.body.description);const st=(await sql('SELECT * FROM students WHERE id=$1',[sid]))[0];if(!st)return res.status(404).json({error:'Student not found.'});if(req.user.role==='teacher'&&!await teacherCanClass(req.user.id,st.class_id))return res.status(403).json({error:'Forbidden'});if(!description||amount<0||paid<0||paid>amount)return res.status(400).json({error:'Invalid fee data.'});const status=paid>=amount?'Paid':paid>0?'Partly Paid':'Unpaid';res.json((await sql('INSERT INTO fees(student_id,description,amount,paid_amount,due_date,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[sid,description,amount,paid,req.body.due_date||null,status]))[0])});
app.get('/api/notices',auth,async(req,res)=>{const aud=req.user.role==='admin'?['all','teacher','student']:[req.user.role,'all'];res.json(await sql('SELECT * FROM notices WHERE audience=ANY($1::text[]) ORDER BY created_at DESC,id DESC',[aud]));});
app.post('/api/notices',auth,only('admin'),async(req,res)=>{const title=norm(req.body.title),message=norm(req.body.message),aud=norm(req.body.audience)||'all';if(!title||!message||!['all','teacher','student'].includes(aud))return res.status(400).json({error:'Invalid notice.'});res.json((await sql('INSERT INTO notices(title,message,audience) VALUES($1,$2,$3) RETURNING *',[title,message,aud]))[0])});
app.get('/api/inventory',auth,only('admin'),async(_req,res)=>res.json(await sql('SELECT * FROM inventory ORDER BY item_name')));
app.post('/api/inventory',auth,only('admin'),async(req,res)=>{const name=norm(req.body.item_name),q=n(req.body.quantity),u=norm(req.body.unit)||'pcs',r=n(req.body.reorder_level,5);if(!name||q<0||r<0)return res.status(400).json({error:'Invalid inventory data.'});res.json((await sql('INSERT INTO inventory(item_name,quantity,unit,reorder_level) VALUES($1,$2,$3,$4) ON CONFLICT(item_name) DO UPDATE SET quantity=$2,unit=$3,reorder_level=$4,updated_at=now() RETURNING *',[name,q,u,r]))[0])});
app.get('/api/admin/settings',auth,only('admin'),async(_req,res)=>res.json((await sql('SELECT * FROM settings WHERE id=1'))[0]||{}));
app.put('/api/admin/settings',auth,only('admin'),async(req,res)=>{const b=req.body||{};res.json((await sql('UPDATE settings SET school_name=$1,school_address=$2,session=$3,term=$4,report_date=$5,developer_name=$6,developer_year=$7,system_open=$8,report_hold=$9,payment_link=$10,maintenance_message=$11 WHERE id=1 RETURNING *',[norm(b.school_name),norm(b.school_address),norm(b.session),norm(b.term),b.report_date||null,norm(b.developer_name)||'Usman Adamu Auwal',norm(b.developer_year)||'2025/2026',b.system_open!==false,b.report_hold===true,norm(b.payment_link),norm(b.maintenance_message)||'The school portal is temporarily closed by the Administrator.']))[0])});

function autoRemarks(avg,failed){const a=n(avg);if(failed||a<40)return {teacher:'The student needs serious improvement and closer supervision. / يحتاج الطالب إلى تحسين كبير ومتابعة مستمرة.',headmaster:'Academic performance is below the required standard. / المستوى الدراسي دون المستوى المطلوب.'};if(a<60)return {teacher:'Fair performance. More effort is required. / أداء مقبول ويحتاج إلى مزيد من الجهد.',headmaster:'The student should work harder next term. / ينبغي للطالب بذل جهد أكبر في الفصل القادم.'};if(a<70)return {teacher:'Good progress. Keep improving. / تقدم جيد، استمر في التحسن.',headmaster:'Good performance with room for further improvement. / أداء جيد مع وجود مجال لمزيد من التحسن.'};if(a<80)return {teacher:'Very good performance. Keep it up. / أداء جيد جداً، واصل على هذا المستوى.',headmaster:'Very good academic performance. / أداء دراسي جيد جداً.'};return {teacher:'Excellent performance. Keep maintaining this standard. / أداء ممتاز، حافظ على هذا المستوى.',headmaster:'Excellent result. May the student continue to excel. / نتيجة ممتازة، نسأل الله له دوام التفوق.'}}
async function calculatePosition(classId,studentId){const rows=await sql(`WITH totals AS (SELECT s.id,COALESCE(SUM(COALESCE(m.total,0)),0) total FROM students s LEFT JOIN marks m ON m.student_id=s.id WHERE s.class_id=$1 GROUP BY s.id) SELECT id,total,DENSE_RANK() OVER(ORDER BY total DESC) position,COUNT(*) OVER() out_of FROM totals`,[classId]);const me=rows.find(r=>Number(r.id)===Number(studentId));return me?{position:String(me.position),out_of:String(me.out_of)}:{position:'',out_of:''}}

async function getStudentForUser(sid,user){const st=(await sql('SELECT s.*,c.name class_name,u.username FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN users u ON u.id=s.user_id WHERE s.id=$1',[sid]))[0];if(!st)return null;if(user.role==='student'&&st.user_id!==user.id)return null;if(user.role==='teacher'&&!await teacherCanClass(user.id,st.class_id))return null;return st}
app.get('/api/report-meta/:studentId',auth,async(req,res)=>{const st=await getStudentForUser(n(req.params.studentId),req.user);if(!st)return res.status(403).json({error:'Forbidden'});res.json((await sql('SELECT * FROM report_meta WHERE student_id=$1',[st.id]))[0]||{})});
app.put('/api/report-meta/:studentId',auth,only('admin','teacher'),async(req,res)=>{const st=await getStudentForUser(n(req.params.studentId),req.user);if(!st)return res.status(403).json({error:'Forbidden'});const b=req.body||{};res.json((await sql(`INSERT INTO report_meta(student_id,position,out_of,attendance_override,teacher_remarks,headmaster_remarks,report_date) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(student_id) DO UPDATE SET position=$2,out_of=$3,attendance_override=$4,teacher_remarks=$5,headmaster_remarks=$6,report_date=$7,updated_at=now() RETURNING *`,[st.id,norm(b.position)||null,norm(b.out_of)||null,norm(b.attendance_override)||null,norm(b.teacher_remarks),norm(b.headmaster_remarks),b.report_date||null]))[0])});
app.get('/api/reports/:studentId',auth,async(req,res)=>{const st=await getStudentForUser(n(req.params.studentId),req.user);if(!st)return res.status(403).json({error:'Forbidden'});let rows=await sql(`SELECT sub.id subject_id,sub.name subject,COALESCE(m.test1,0) test1,COALESCE(m.test2,0) test2,COALESCE(m.exam,0) exam,COALESCE(m.total,0) total,m.manual_total,m.manual_grade FROM subjects sub LEFT JOIN marks m ON m.subject_id=sub.id AND m.student_id=$1 ORDER BY sub.id`,[st.id]);rows=rows.map(r=>{const g=grade(r.total),manual=norm(r.manual_grade);const total=n(r.total);const fail=total<40 || (manual?/poor|كسلان|fail|راسب/i.test(manual):g.fail);const label=total<40?'كسلان / Poor':(manual||g.label);return {...r,test1:n(r.test1),test2:n(r.test2),exam:n(r.exam),total,grade:label,grade_color:fail?'#b42318':g.color,fail}});const sum=rows.reduce((a,r)=>a+r.total,0),avg=rows.length?Math.round(sum/rows.length*100)/100:0,overall_fail=rows.some(r=>r.fail)||avg<40;const cfg=(await sql('SELECT * FROM settings WHERE id=1'))[0]||{};const meta=(await sql('SELECT * FROM report_meta WHERE student_id=$1',[st.id]))[0]||{};const att=(await sql(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE LOWER(status)='present')::int present FROM attendance WHERE student_id=$1`,[st.id]))[0]||{total:0,present:0};const pos=await calculatePosition(st.class_id,st.id);const auto=autoRemarks(avg,overall_fail);res.json({student:st,rows,total:sum,average:avg,overall_fail,school_name:cfg.school_name||'AL-FAUZAN CENTER FOR QUR\'AN AND GENERAL STUDIES',school_address:cfg.school_address||'KUKAR AUWALE, ALIERO, KEBBI STATE',session:cfg.session||'2025/2026',term:cfg.term||'First Term',report_date:meta.report_date||cfg.report_date||new Date().toISOString().slice(0,10),position:meta.position||pos.position,out_of:meta.out_of||pos.out_of,attendance:meta.attendance_override||(att.total?`${att.present}/${att.total}`:''),teacher_remarks:meta.teacher_remarks||auto.teacher,headmaster_remarks:meta.headmaster_remarks||auto.headmaster,developer_name:cfg.developer_name||'Usman Adamu Auwal',developer_year:cfg.developer_year||'2025/2026',report_held:cfg.report_hold===true,payment_link:cfg.payment_link||'',system_open:cfg.system_open!==false})});

app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Server error.'})});
init().then(()=>app.listen(PORT,()=>console.log(`Al-Fauzan SMS API listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
